name: Build

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: npm install, build, and test
      run: |
        npm ci
        npm run lint:js
        npm run build --if-present
        npm test
      env:
        CI: true
